name: Build with Quality Check
on:
  push:
    branches:
      - "*"
  workflow_call:

jobs:
  build-deb:
    uses: ./.github/workflows/build-deb.yml
  build-rpm:
    uses: ./.github/workflows/build-rpm.yml
